### ISSUE TITLE
Cart Entity

### ISSUE THREAD

**Issue by charangajjala** [charangajjala/medEase_portal#15]
1. Implmnt Cart logic in both sides
2. IN DB, Cart has list of products and one User
3. If same product is addes to cart, increase quantity else, add that procduct with quantity with one
4. Maintain total price field and also price of each product

**Comment by Prem01-cyber** [comment]
The cart functions effectively in both the frontend and backend, and the requisite user interface enhancements have been implemented. However, managing PUT requests within POST could be problematic, as there are scenarios where we need to modify the product quantity without changing the quantity value itself.
