### ISSUE TITLE
Fix SecurityConfig

### ISSUE THREAD

**Issue by charangajjala** [charangajjala/medEase_portal#4]
- Disable authentication for /api/login path
- Enable authentication for any other route
![image](https://github.com/charangajjala/medEase_portal/assets/64437927/1480bd41-47c4-414d-aff1-b51c91b130cc)

**Comment by Prem01-cyber** [comment]
The issue mainly resists with the /api context addition upon adding this WHITE_LIST_URLs should also be updated accordingly
